name: Playwright Tests
on: [pull_request, push]
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Install dependencies
              run: npm ci
            - name: Run lint
              run: npm run lint
            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
            - name: Run Playwright tests
              run: npx playwright test
              env:
                  NEXT_PUBLIC_THE_MOVIE_DB_V3_API_KEY: ${{ secrets.NEXT_PUBLIC_THE_MOVIE_DB_V3_API_KEY }}
                  NEXT_PUBLIC_THE_MOVIE_DB_V3_BASE_URL: ${{ secrets.NEXT_PUBLIC_THE_MOVIE_DB_V3_BASE_URL }}
